---
- name: make sure www-data home directory exists
  file: path=/var/www owner=www-data group=www-data mode=0700 state=directory

- name: make sure www-data home directory exists
  file: path=/var/www/.ssh owner=www-data group=www-data mode=0700 state=directory

- name: ssh | setup ssh access for www-data user
  authorized_key: user=www-data key="{{ item }}"
  with_file:
    - public_keys/enter_key_name